common:
  data_path: data/wallet_addresses.txt
  trend_analysis_report_path: output/trend_analysis_report.txt
  transaction_analysis_report_path: output/transaction_analysis_report.txt
  behavioral_classification_path: output/behavioral_classification_report.txt
  wallet_age_report_path: output/wallet_age_report.txt
  etherscan_base_url: https://etherscan.io/address

agent:
  model: gpt-4o-mini
  chatbot_model_name: meta-llama/Llama-3.2-3B-Instruct
  rate_limit_delay: 2
  temperature: 0.0
  top_p: 0.8
  max_tokens: 2000